on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainerregistry9090.azurecr.io
        username: ${{ secrets.acr_mycontainerregistry9090_username }}
        password: ${{ secrets.acr_mycontainerregistry9090_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t mycontainerregistry9090.azurecr.io/kubernetescluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push mycontainerregistry9090.azurecr.io/kubernetescluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernetescluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetescluster9889 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetescluster9889`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetescluster9889
        container-registry-url: mycontainerregistry9090.azurecr.io
        container-registry-username: ${{ secrets.acr_mycontainerregistry9090_username }}
        container-registry-password: ${{ secrets.acr_mycontainerregistry9090_password }}
        secret-name: kubernetescldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernetescluster9889
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mycontainerregistry9090.azurecr.io/kubernetescluster:${{ github.sha }}
        imagepullsecrets: |
          kubernetescldockerauth
